{% set name = "cuda-cuxxfilt" %}
{% set version = "13.4.49" %}
{% set cuda_version = "13.4" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win64]
{% set platform = "windows-arm64" %}  # [win and arm64]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win64]
{% set target_name = "arm64" %}  # [win and arm64]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]
{% set sha256 = "38949b20b4fdbc327a4540370c962c71479f556f70582c17a578225a9b28d1bc" %}  # [linux64]
{% set sha256 = "7df3c67dbea9c266b436fa3b892b23539fcaf63ab9c8e7b945c3f8e24be4f507" %}  # [aarch64]
{% set sha256 = "4f665e4df32ebe9cdecb4b6eaf408d8e0321cf126e87384c0358cc2aee4317e1" %}  # [win64]
{% set sha256 = "a5be73787be102164d4c8d83fdaf9464b5e97865614ba33f6103d8123fbd6921" %}  # [win and arm64]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_cuxxfilt/{{ platform }}/cuda_cuxxfilt-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: {{ sha256 }}

build:
  number: 1
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}

test:
  requires:
    - patchelf  # [linux]
  files:
    - test-rpath.sh
  commands:
    - test -f $PREFIX/bin/cu++filt                                   # [linux]
    - test -f $PREFIX/targets/{{ target_name }}/include/nv_decode.h  # [linux]
    - test -f $PREFIX/targets/{{ target_name }}/lib/libcufilt.a      # [linux]
    - bash test-rpath.sh                                             # [linux]
    - if not exist %LIBRARY_BIN%\cu++filt.exe exit 1                 # [win]
    - if not exist %LIBRARY_INC%\\nv_decode.h exit 1                 # [win]
    - if not exist %LIBRARY_LIB%\{{ target_name }}\cufilt.lib exit 1  # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: cu++filt decodes low-level identifiers that have been mangled by CUDA C++
  description: |
    cu++filt decodes (demangles) low-level identifiers that have been mangled by
    CUDA C++ into user readable names. For every input alphanumeric word, the
    output of cu++filt is either the demangled name if the name decodes to a CUDA
    C++ name, or the original name itself.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
